# -*- mode: yaml -*-
# vim:ts=2:sw=2:ai:si:syntax=yaml
#
# pre-commit hook configuration
# https://pre-commit.com/
---
minimum_pre_commit_version: "1.20"

default_language_version:
  python: python3
  node: "12.14.1"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.4.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md"]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-yaml
      - id: check-ast
      - id: requirements-txt-fixer

  # Format JSON, Markdown and YAML files with Prettier.
  - repo: https://github.com/prettier/prettier
    rev: "1.19.1"
    hooks:
      - id: prettier
        name: Format JSON, Markdown and YAML files
        files: "\\.(\
          json\
          |md|markdown|mdown|mkdn\
          |yaml|yml\
          )$"
        # Do not run on Git push
        stages: [commit]

  - repo: https://github.com/pre-commit/mirrors-yapf.git
    rev: v0.28.0
    hooks:
      - id: yapf
        exclude: ^playbooks/library/luarocks\.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.2.3
    hooks:
      - id: flake8
        exclude: ^playbooks/library/luarocks\.py$

  # Validate Python code with pylint using local environment
  # to avoid 'import-error' issues.
  - repo: local
    hooks:
      - id: pylint
        name: Lint Python files with pylint
        entry: python -m pylint
        types: [python]
        language: system
        require_serial: false
        exclude: ^playbooks/library/luarocks\.py$

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.18.0
    hooks:
      - id: yamllint

  - repo: https://github.com/ansible/ansible-lint.git
    rev: v4.1.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.16
    hooks:
      - id: shellcheck
      - id: shfmt
        args: ["-l", "-i", "4", "-ci", "-w"]

  - repo: https://github.com/openstack-dev/bashate.git
    rev: "0.6.0"
    hooks:
      - id: bashate
        args: ["-i", "E006"]
        verbose: false

  - repo: https://github.com/igorshubovych/markdownlint-cli.git
    rev: v0.19.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/markosamuli/pre-commit-travis-lint
    rev: v1.8.8
    hooks:
      - id: travis-lint

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook.git
    rev: v2.1.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
        verbose: false
